### ISSUE TITLE
V20 Support?

### ISSUE THREAD

**Issue by WindowsAurora** [luizoti/skin.xperience1080#11]
Can You Add Official Nexus Support?

**Comment by luizoti** [comment]
> Can You Add Official Nexus Support?

I remember that it worked, but I haven't used KODI in a while, I'm going to use it again in the next few days and if I have to make any adjustments I'll take a look.

**Comment by luizoti** [comment]
Only to update, the original Developer update the skin to work on Nexus, but apparently is out of Kodi Official Repo, i recently install my version on Nexus end works, but i don´t kwon if all functions is ok.
My Repo (host my version of skin):
https://github.com/luizoti/repository.melies/blob/master/repository.melies-0.1.5.zip
