### ISSUE TITLE
OSD season/episode not show E for EP

### ISSUE THREAD

**Issue by luizoti** [luizoti/skin.xperience1080#7]
Necessary for Leia and Matrix

**Comment by blunden** [comment]
Hasn't this already been fixed? It looks like it to me, but maybe I'm looking in the wrong place in the UI. :)

**Comment by luizoti** [comment]
I must have corrected it and forgot to close the issue.

**Comment by blunden** [comment]
I'm guessing this issue refers to the one fixed by the commit linked below?

https://github.com/luizoti/skin.xperience1080/commit/2b8a972588103ddd94a2868427f21a60113428b0

**Comment by luizoti** [comment]
Fixed in 2b8a972588103ddd94a2868427f21a60113428b0

Thx @blunden .
