### ISSUE TITLE
Android support?

### ISSUE THREAD

**Issue by rrrevin** [luizoti/skin.xperience1080#8]
Have you or anyone else tried this for Android?
I'm thinking any of the smaller Android based TV/Movie playing devices.. think G-Box and the like.

**Comment by blunden** [comment]
I just tried it on my phone. While it works, some UI elements don't scale properly for screens that aren't 16:9. The touch support is also pretty bad, and mouse support is non-existant. If you try it on a device connected to a TV it might be ok though. It should at least be functional enough for you switch back after trying it if you don't like it.

To install the flat skin called Metro in the readme, the path on Android is: /sdcard/Android/data/.kodi/addons/skin.xperience1080/media/

Note that I had the same scaling issues in a Linux VM as well that went away when I set a 16:9 resolution so as long as you don't need touch or mouse support it's likely to be fine.

**Comment by luizoti** [comment]
Originally the theme was created without mouse support, anyway, not the original dev said it's going back to the project (who knows when), I don't intend to make any big changes myself.

**Comment by blunden** [comment]
Yeah, I don't think a lack of touch and mouse support is an issue for most people since they are more likely to run it on a device connected to their TV.

**Comment by luizoti** [comment]
yep, i agree.
