### ISSUE TITLE
OSD for fast-forwarding using D-pad missing

### ISSUE THREAD

**Issue by blunden** [luizoti/skin.xperience1080#9]
Skipping forward or backward using a D-pad (common with many media player remotes) used to show how far you were skipping along using the OSD back in Leia. This is no longer the case.

I'm guessing Matrix made some changes to the playback OSD.

**Comment by blunden** [comment]
It seems there are supposed to be settings for this based on some previous commits. I see a setting for hiding the progress bar as well as two toggles without text strings.

Hide Progress Bar
[No string]
Hide Chapter Information
[No string]

**Comment by luizoti** [comment]
As far as I can remember as the default for the progress bar to be displayed, at least it should be like this.

The option "Hide Chapter Information" hides the widget that shows the chapter of the movie\show you are watching, when this information does not exist.

**Comment by luizoti** [comment]
If you're still having problems, try to update the theme, but here it looks ok, below print with all options turned off.


![Screenshot_20220119_022510](https://user-images.githubusercontent.com/29931919/150069494-329d9b2d-921e-480d-bc41-6602067800b9.png)
